### ISSUE TITLE
Error when running python scripts/trace_repos.py

### ISSUE THREAD

**Issue by j991222** [lean-dojo/ReProver#29]
I encountered an error when running python scripts/trace_repos.py(CONTAINER="native"). The error message is as follows:
```
2023-10-01 12:31:32.387 | DEBUG    | lean_dojo.data_extraction.lean:_parse_lakefile_dependencies:503 - Querying the commit hash for https://github.com/leanprover/doc-gen4 "main"
2023-10-01 12:31:36.338 | DEBUG    | lean_dojo.utils:read_url:238 - Requset to https://github.com/leanprover/lean4-nightly/releases/tag/v4.1.0 failed. Retrying...
Traceback (most recent call last):
  File "/home/username/extractdata/extract.py", line 7, in <module>
    trace(repo)
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/trace.py", line 164, in trace
    traced_repo = TracedRepo.load_from_disk(cached_path)
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/traced_data.py", line 1481, in load_from_disk
    dependencies = repo.get_dependencies(root_dir)
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/lean.py", line 461, in get_dependencies
    return self._get_lean4_dependencies(path)
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/lean.py", line 524, in _get_lean4_dependencies
    for name, repo in self._parse_lakefile_dependencies(lakefile):
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/lean.py", line 507, in _parse_lakefile_dependencies
    deps.append((m["name"], LeanGitRepo(url, commit)))
  File "<string>", line 5, in __init__
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/lean.py", line 400, in __post_init__
    lean_version = get_lean4_commit_from_config(config)
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/data_extraction/lean.py", line 297, in get_lean4_commit_from_config
    html = read_url(url)
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/utils.py", line 236, in read_url
    raise ex
  File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/lean_dojo/utils.py", line 232, in read_url
    with urllib.request.urlopen(url) as f:
  File "/home/username/.conda/envs/myenv/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/username/.conda/envs/myenv/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/home/username/.conda/envs/myenv/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/home/username/.conda/envs/myenv/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/home/username/.conda/envs/myenv/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/username/.conda/envs/myenv/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by yangky11** [comment]
What is the version of LeanDojo you're using? Upgrading to the latest version (`v1.2.5`) may solve the problem.

**Comment by j991222** [comment]
I updated to v1.2.5 and ran python scripts/trace_repos.py(CONTAINER='native'). Now the error message is
```
2023-10-03 13:06:46.114 | DEBUG    | lean_dojo.data_extraction.traced_data:load_from_disk:1480 - Loading 4264 traced XML files from /home/username/.cache/lean_dojo/leanprover-community-mathlib4-355541ae7a2455222f179dcf7f074aa2c45eb8aa/mathlib4 with 31 workers
2023-10-03 13:06:48,523 INFO worker.py:1612 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
  0%|                                                                                                                   | 0/4264 [00:00<?, ?it/s](pid=143565) 2023-10-03 13:06:50.892 | DEBUG    | lean_dojo.constants:<module>:72 - Using GitHub without authentication. Don't be surprised if you hit the API rate limit.
(TemporaryActor pid=143584) 'lean_dojo'
(TemporaryActor pid=143584) Traceback (most recent call last):
(TemporaryActor pid=143584)   File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/ray/_private/serialization.py", line 387, in deserialize_objects
(TemporaryActor pid=143584)     obj = self._deserialize_object(data, metadata, object_ref)
(TemporaryActor pid=143584)   File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/ray/_private/serialization.py", line 268, in _deserialize_object
(TemporaryActor pid=143584)     return self._deserialize_msgpack_data(data, metadata_fields)
(TemporaryActor pid=143584)   File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/ray/_private/serialization.py", line 223, in _deserialize_msgpack_data
(TemporaryActor pid=143584)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(TemporaryActor pid=143584)   File "/home/username/.conda/envs/myenv/lib/python3.10/site-packages/ray/_private/serialization.py", line 213, in _deserialize_pickle5_data
(TemporaryActor pid=143584)     obj = pickle.loads(in_band)
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap>", line 945, in _find_spec
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap_external>", line 1405, in _get_spec
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap_external>", line 1255, in __iter__
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap_external>", line 1242, in _recalculate
(TemporaryActor pid=143584)   File "<frozen importlib._bootstrap_external>", line 1238, in _get_parent_path
(TemporaryActor pid=143584) KeyError: 'lean_dojo'
(TemporaryActor pid=143584) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::_TracedRepoHelper.__init__() (pid=143584, ip=my_ip, actor_id=3fb76f64e35a7497be1d64e101000000, repr=<lean_dojo.data_extraction.traced_data.FunctionActorManager._create_fake_actor_class.<locals>.TemporaryActor object at 0x7f3ec2c6d9c0>)
(TemporaryActor pid=143584)   At least one of the input arguments for this task could not be computed:
(TemporaryActor pid=143584) ray.exceptions.RaySystemError: System error: 'lean_dojo'
```
