### ISSUE TITLE
"ValueError: Tensors must be contiguous" when training ReProver (CUDA 12.4)

### ISSUE THREAD

**Issue by realharryhero** [lean-dojo/ReProver#66]
Hello,

When I follow all the instructions (including setting up a conda environment), I recieve the following error:
<details><summary><b>Log</b></summary>
<p>

```
[2024-07-26 19:20:55,224] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
2024-07-26 19:20:55.838 | INFO     | __main__:main:19 - PID: 108346
Seed set to 3407
2024-07-26 19:20:56.872 | INFO     | common:__init__:200 - Building the corpus from data/leandojo_benchmark_4/corpus.jsonl
2024-07-26 19:21:10.642 | INFO     | generation.datamodule:__init__:147 - Without retrieval data
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
[rank: 0] Seed set to 3407
initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/1
wandb: Currently logged in as: [REDACTED] ([REDACTED]). Use `wandb login --relogin` to force relogin
wandb: WARNING Path logs/train_generator_novel_premises/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path logs/train_generator_novel_premises/wandb/ wasn't writable, using system temp directory
wandb: Tracking run with wandb version 0.17.5
wandb: Run data is saved locally in /tmp/wandb/run-20240726_192111-iykqoyqi
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run train_generator_novel_premises
wandb: ⭐️ View project at https://wandb.ai/[REDACTED]/lightning_logs
wandb: 🚀 View run at https://wandb.ai/[REDACTED]/lightning_logs/runs/iykqoyqi
100%|██████████████████████████████████████████| 118517/118517 [00:00<00:00, 574149.48it/s]
2024-07-26 19:21:21.894 | INFO     | generation.datamodule:_load_data:60 - 246714 examples loaded
100%|██████████████████████████████████████████████| 2000/2000 [00:00<00:00, 527088.16it/s]
2024-07-26 19:21:21.956 | INFO     | generation.datamodule:_load_data:60 - 6240 examples loaded
Enabling DeepSpeed BF16. Model parameters and inputs will be cast to `bfloat16`.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2024-07-26 19:21:22.041 | INFO     | common:get_optimizers:392 - Optimizing with FusedAdam
Using /home/mfan/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/mfan/.cache/torch_extensions/py310_cu121/fused_adam/build.ninja...
/home/mfan/ReProver/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /home/mfan/ReProver/lib/python3.10/site-packages/torch/include -isystem /home/mfan/ReProver/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/mfan/ReProver/lib/python3.10/site-packages/torch/include/TH -isystem /home/mfan/ReProver/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_86,code=sm_86 -gencode=arch=compute_86,code=compute_86 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ -std=c++17 -c /home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
[2/2] c++ fused_adam_frontend.o multi_tensor_adam.cuda.o -shared -L/home/mfan/ReProver/lib/python3.10/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart -o fused_adam.so
Loading extension module fused_adam...
Time to load fused_adam op: 14.073747634887695 seconds
Traceback (most recent call last):
  File "/home/mfan/ReProver/generation/main.py", line 25, in <module>
    main()
  File "/home/mfan/ReProver/generation/main.py", line 20, in main
    cli = CLI(RetrievalAugmentedGenerator, GeneratorDataModule)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 394, in __init__
    self._run_subcommand(self.subcommand)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 701, in _run_subcommand
    fn(**fn_kwargs)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 543, in fit
    call._call_and_handle_interrupt(
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in _run
    self.strategy.setup(self)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 350, in setup
    self.init_deepspeed()
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 451, in init_deepspeed
    self._initialize_deepspeed_train(self.model)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 487, in _initialize_deepspeed_train
    model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 423, in _setup_model_and_optimizer
    deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/__init__.py", line 181, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1148, in _configure_distributed_model
    self._broadcast_model()
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1068, in _broadcast_model
    dist.broadcast(p.data, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 199, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/home/mfan/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2140, in broadcast
    work = group.broadcast([tensor], opts)
ValueError: Tensors must be contiguous
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/mfan/ReProver/generation/main.py", line 25, in <module>
[rank0]:     main()
[rank0]:   File "/home/mfan/ReProver/generation/main.py", line 20, in main
[rank0]:     cli = CLI(RetrievalAugmentedGenerator, GeneratorDataModule)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 394, in __init__
[rank0]:     self._run_subcommand(self.subcommand)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 701, in _run_subcommand
[rank0]:     fn(**fn_kwargs)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 543, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in _run
[rank0]:     self.strategy.setup(self)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 350, in setup
[rank0]:     self.init_deepspeed()
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 451, in init_deepspeed
[rank0]:     self._initialize_deepspeed_train(self.model)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 487, in _initialize_deepspeed_train
[rank0]:     model, deepspeed_optimizer = self._setup_model_and_optimizer(model, optimizer, scheduler)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/pytorch_lightning/strategies/deepspeed.py", line 423, in _setup_model_and_optimizer
[rank0]:     deepspeed_engine, deepspeed_optimizer, _, _ = deepspeed.initialize(
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/__init__.py", line 181, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
[rank0]:     self._configure_distributed_model(model)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1148, in _configure_distributed_model
[rank0]:     self._broadcast_model()
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1068, in _broadcast_model
[rank0]:     dist.broadcast(p.data, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
[rank0]:     return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 199, in broadcast
[rank0]:     return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/mfan/ReProver/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2140, in broadcast
[rank0]:     work = group.broadcast([tensor], opts)
[rank0]: ValueError: Tensors must be contiguous
wandb: 🚀 View run train_generator_novel_premises at: https://wandb.ai/[REDACTED]/lightning_logs/runs/iykqoyqi
wandb: ⭐️ View project at: https://wandb.ai/[REDACTED]/lightning_logs
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: /tmp/wandb/run-20240726_192111-iykqoyqi/logs
wandb: WARNING The new W&B backend becomes opt-out in version 0.18.0; try it out with `wandb.require("core")`! See https://wandb.me/wandb-core for more information.
```

</p>
</details> 

I'm using CUDA 12.4, so that could be an issue. Otherwise, a [result on StackOverflow](https://stackoverflow.com/questions/48915810/what-does-contiguous-do-in-pytorch) seems to summarize what's occurring. If so, where would the .contiguous() function go? Thanks!

**Comment by yangky11** [comment]
What was the command that triggered this error?

**Comment by yangky11** [comment]
I wasn't able to reproduce the error. From the logs, it looks like the error is in PyTorch Lightning or DeepSpeed. So I don't think adding a `. contiguous()` in ReProver would actually help. Have you tried creating a new conda environment and re-install those dependencies?

**Comment by huolongguo1O** [comment]
> I wasn't able to reproduce the error. From the logs, it looks like the error is in PyTorch Lightning or DeepSpeed. So I don't think adding a `. contiguous()` in ReProver would actually help. Have you tried creating a new conda environment and re-install those dependencies?

在4090和3080Ti上遇到同样的问题，能不能支持不使用deepspeed

**Comment by yifan123** [comment]
`for param in model.parameters(): param.data = param.data.contiguous()` [https://github.com/huggingface/transformers/issues/28293](url)

After load your model, add this line to convert weight to contiguous, it works for me!
